### ISSUE TITLE
'chakra' org shows up for invalid email addresses

### ISSUE THREAD

**Issue by craigbox** [cncf/gitdm#145]
https://github.com/cncf/gitdm/blob/master/developers_affiliations4.txt#L11602

```
invalid-email-address: a!b.com, git!github.com, invalid-email-address!users.noreply.github.com, root!localhost.localdomain, support!github.com, unconfigured!null.spigotmc.org, vagrant!localhost.localdomain, vagrant!vagrant.vm, you!example.com
	chakra
```

What's up with 'chakra'?  Should it not map to "None" or equivalent so it is filtered out?

Right now devstats shows this:

<img width="715" alt="Screenshot 2023-08-12 at 9 49 13 PM" src="https://github.com/cncf/gitdm/assets/132510/b00816ea-c08e-4158-b454-03a437527d82">

**Comment by lukaszgryglicki** [comment]
I will check this and get back to you - I'm checking all tickets after a PTO/vacation.

**Comment by lukaszgryglicki** [comment]
So in [github_users.json](https://github.com/cncf/gitdm/blob/master/src/github_users.json) file there is an entry:
```
  {
    "login": "invalid-email-address",
    "email": "you!example.com",
    "affiliation": "chakra",
    "source": "config",
    "name": "Check your git settings!",
    "commits": 61
  },
```

This means that the user with an `invalid-email-address` profile has `chakra` as company affiliation, but I don't see such a GitHub profile (maybe it was there in the past) so I will remove that entry for github_users.json and other config files and fix this in a batch of other Prs merge - I will then update here.

**Comment by lukaszgryglicki** [comment]
This is fixed and updated in the repo.
