### ISSUE TITLE
I didn't find my information in this new repository

### ISSUE THREAD

**Issue by YTGhost** [cncf/gitdm#180]
I used to update information about me in this repository(https://github.com/cncf/gitdm.archive), but I now realize that this repository has been archived. And I realized that I couldn't find information about me in this new repository now. What should I do? is it to submit a pr to add my info to this new repository?

**Comment by lukaszgryglicki** [comment]
```
root@darkstar:~/go/src/github.com/cncf/gitdm# grep YTGhost *
company_developers2.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com from 2020-08-01 until 2021-06-01, from 2022-01-01 until 2022-09-01
company_developers2.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com from 2023-03-01
company_developers4.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com from 2021-06-01 until 2022-01-01
company_developers5.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com until 2020-08-01, from 2022-09-01 until 2023-03-01
developers_affiliations2.txt:YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com
```

Also in `github_users.json`:
```
  {
    "login": "YTGhost",
    "email": "283304489!qq.com",
    "affiliation": "Independent < 2020-08-01, Bytedance Ltd < 2021-06-01, HarmonyCloud-谐云科技 < 2022-01-01, Bytedance Ltd < 2022-09-01, Independent < 2023-03-01, CNCF",
    "source": "user",
    "name": "HIHIA",
    "commits": 364,
    "location": "Hangzhou, China",
    "country_id": "cn"
  },
  {
    "login": "YTGhost",
    "email": "YTGhost!users.noreply.github.com",
    "affiliation": "Independent < 2020-08-01, Bytedance Ltd < 2021-06-01, HarmonyCloud-谐云科技 < 2022-01-01, Bytedance Ltd < 2022-09-01, Independent < 2023-03-01, CNCF",
    "source": "user",
    "name": "HIHIA",
    "commits": 364,
    "location": "Hangzhou, China",
    "country_id": "cn"
  },
```

**Comment by YTGhost** [comment]
> ```
> root@darkstar:~/go/src/github.com/cncf/gitdm# grep YTGhost *
> company_developers2.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com from 2020-08-01 until 2021-06-01, from 2022-01-01 until 2022-09-01
> company_developers2.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com from 2023-03-01
> company_developers4.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com from 2021-06-01 until 2022-01-01
> company_developers5.txt:	YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com until 2020-08-01, from 2022-09-01 until 2023-03-01
> developers_affiliations2.txt:YTGhost: 283304489!qq.com, YTGhost!users.noreply.github.com
> ```
> 
> Also in `github_users.json`:
> 
> ```
>   {
>     "login": "YTGhost",
>     "email": "283304489!qq.com",
>     "affiliation": "Independent < 2020-08-01, Bytedance Ltd < 2021-06-01, HarmonyCloud-谐云科技 < 2022-01-01, Bytedance Ltd < 2022-09-01, Independent < 2023-03-01, CNCF",
>     "source": "user",
>     "name": "HIHIA",
>     "commits": 364,
>     "location": "Hangzhou, China",
>     "country_id": "cn"
>   },
>   {
>     "login": "YTGhost",
>     "email": "YTGhost!users.noreply.github.com",
>     "affiliation": "Independent < 2020-08-01, Bytedance Ltd < 2021-06-01, HarmonyCloud-谐云科技 < 2022-01-01, Bytedance Ltd < 2022-09-01, Independent < 2023-03-01, CNCF",
>     "source": "user",
>     "name": "HIHIA",
>     "commits": 364,
>     "location": "Hangzhou, China",
>     "country_id": "cn"
>   },
> ```

I didn't find it using github's search at first, then retrieved it locally, so I closed the issue. Thanks for your reply.
