### ISSUE TITLE
Company name is not showing in k8s devstats 

### ISSUE THREAD

**Issue by Aaina26** [cncf/gitdm#353]
Last week, I submitted PR https://github.com/cncf/gitdm/pull/342 to add affiliation for me and it was also merged.
But the Kubernetes devstats does not show company name with my contribution for v1.30 and v1.31. Here is the link for v1.31:  https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.30.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=All

![Screenshot from 2024-04-24 11-36-50](https://github.com/cncf/gitdm/assets/54260570/60f09e0c-a88e-4c36-8a83-7931da1b7636)

Here is the link for v1.30: https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.29.0%20-%20v1.30.0&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes&var-country_name=All&var-companies=All

![Screenshot from 2024-04-24 11-44-26](https://github.com/cncf/gitdm/assets/54260570/bb287feb-cb13-479b-8860-0362e34b2dff)

**Comment by lukaszgryglicki** [comment]
Affiliations are imported once per 28 days, this is all explained in `cncf/gitdm` updating affiliations documentation, you just need to wait a bit.

**Comment by Aaina26** [comment]
Thank you for resolving my query!
