### ISSUE TITLE
Devstats Dashboard not showing company affiliation for a Radius contributor

### ISSUE THREAD

**Issue by Reshrahim** [cncf/gitdm#392]
For some users the [developer activity by count](https://radius.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1) is not showing up though this repository has company affiliation data

User - superbeeny
![image](https://github.com/cncf/gitdm/assets/61033581/27c4cc8e-5c1a-453a-9ba4-2471fc1a235e)

![image](https://github.com/cncf/gitdm/assets/61033581/9b5831e8-0249-4692-91b3-8ba5aa65be1b)

**Comment by lukaszgryglicki** [comment]
Affiliations are imported once a 28 days, I'll check this case, maybe this wasn't imported yet.

**Comment by lukaszgryglicki** [comment]
Right, so given use indeed has affiliations (checked `github_users.json` file) but they weren't imported yet, see:
```
radius=# select * from gha_actors_affiliations where actor_id = (select id from gha_actors where login = 'superbeeny');
 actor_id | company_name | original_company_name | dt_from | dt_to | source 
----------+--------------+-----------------------+---------+-------+--------
(0 rows)
```

I'll import them manually now.

**Comment by lukaszgryglicki** [comment]
The last import was 27 days ago:
```
root@devstats-node-2:~/go/src/github.com/cncf/devstats-k8s-lf/util# k get po -A | grep affiliations-radius
devstats-prod    devstats-affiliations-radius-1713793560-z5867                    0/1     Completed   0          31d
devstats-prod    devstats-affiliations-radius-1714194000-nwdqb                    0/1     Completed   0          27d
```

**Comment by lukaszgryglicki** [comment]
Now affs are imported and already in the database:
```
radius=# select id from gha_actors where login = 'superbeeny';
   id    
---------
 1985327
(1 row)

radius=# select * from gha_actors_affiliations where actor_id = (select id from gha_actors where login = 'superbeeny');
 actor_id |                company_name                |           original_company_name            |       dt_from       |        dt_to        | source 
----------+--------------------------------------------+--------------------------------------------+---------------------+---------------------+--------
  1985327 | Comcast Cable Communications LLC (Xfinity) | Comcast Cable Communications LLC (Xfinity) | 1900-01-01 00:00:00 | 2100-01-01 00:00:00 | manual
(1 row)
```

Now it will regenerate dashboards to show the new data...

**Comment by lukaszgryglicki** [comment]
This is fixed:
<img width="2365" alt="Zrzut ekranu 2024-05-24 o 09 46 07" src="https://github.com/cncf/gitdm/assets/2469783/bc472100-11f1-41b6-9620-3b71eafcea57">

**Comment by Reshrahim** [comment]
Thanks a lot @lukaszgryglicki for checking on this and providing a fix! I do see affiliations for some other users updated as well.
