### ISSUE TITLE
Question: unexpected data about developers activity counts in CNCF

### ISSUE THREAD

**Issue by steverao** [cncf/gitdm#394]
1. My colleagues's GitHub ID is `ralf0131`. I added his company name in [PR](https://github.com/cncf/gitdm/pull/338/files) and also check there is his information.
![image](https://github.com/cncf/gitdm/assets/25423978/09a516d5-3423-4be7-8c0d-9f0b5c6c7552)
But in dashboard, it doesn't show his company name. It seems be a same problem with #373
![image](https://github.com/cncf/gitdm/assets/25423978/22472f4c-5fe7-4aad-8722-f160a336a5b4)

2. Also, He left several comments in different OTel repositories. I also download relevant his GitHub data in below file:
[aggregated_filtered_files.json](https://github.com/cncf/gitdm/files/15419077/aggregated_filtered_files.json)
In an issue, he left five comments, why does it just show two numbers in dashboard like above figure?

**Comment by lukaszgryglicki** [comment]
I'm checking this now.

**Comment by lukaszgryglicki** [comment]
OK so rolls were imported:
```
opentelemetry=# select * from gha_actors_affiliations where actor_id in (select id from gha_actors where login = 'ralf0131');
       actor_id       | company_name  | original_company_name |       dt_from       |        dt_to        | source 
----------------------+---------------+-----------------------+---------------------+---------------------+--------
              4397305 | Independent   | Independent           | 1900-01-01 00:00:00 | 2014-08-04 00:00:00 | user
              4397305 | Alibaba Group | Alibaba Group         | 2014-08-04 00:00:00 | 2100-01-01 00:00:00 | user
 -3340025100464355191 | Independent   | Independent           | 1900-01-01 00:00:00 | 2014-08-04 00:00:00 | user
 -3340025100464355191 | Alibaba Group | Alibaba Group         | 2014-08-04 00:00:00 | 2100-01-01 00:00:00 | user
(4 rows)
```

Those are all activities for this user so far:
```
opentelemetry=# select * from gha_events where dup_actor_login = 'ralf0131' and created_at > now() - '3 months'::interval and type like 'IssueCommentEvent' and dup_repo_name = 'open-telemetry/community' order by created_at;
     id      |       type        | actor_id |  repo_id  | public |     created_at      |  org_id  | forkee_id | dup_actor_login |      dup_repo_name       
-------------+-------------------+----------+-----------+--------+---------------------+----------+-----------+-----------------+--------------------------
 38421241763 | IssueCommentEvent |  4397305 | 184620732 | t      | 2024-05-16 03:27:16 | 49998002 |           | ralf0131        | open-telemetry/community
 38463506577 | IssueCommentEvent |  4397305 | 184620732 | t      | 2024-05-17 07:05:09 | 49998002 |           | ralf0131        | open-telemetry/community
 38503640303 | IssueCommentEvent |  4397305 | 184620732 | t      | 2024-05-19 02:22:46 | 49998002 |           | ralf0131        | open-telemetry/community
 38559873642 | IssueCommentEvent |  4397305 | 184620732 | t      | 2024-05-21 08:30:06 | 49998002 |           | ralf0131        | open-telemetry/community
 38570999094 | IssueCommentEvent |  4397305 | 184620732 | t      | 2024-05-21 13:52:17 | 49998002 |           | ralf0131        | open-telemetry/community
 38573018480 | IssueCommentEvent |  4397305 | 184620732 | t      | 2024-05-21 14:45:47 | 49998002 |           | ralf0131        | open-telemetry/community
(6 rows)
```

6 issue comments and [the dashboard](https://opentelemetry.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20quarter&var-metric=contributions&var-repogroup_name=open-telemetry%2Fcommunity&var-country_name=All&var-companies=All) shows 6 contributions with `Alibaba Group` company - so after manually refreshing data, all is OK - again please note that those dashboards are NOT realtime - 1st - affiliations are imported once / 4 weeks and dashboards are generated at given point in time and "saved" in precomputed tables so they are quickly displayed on the UI, you can check what time given dashboard was last calculated by looking at [Last Updated](https://opentelemetry.devstats.cncf.io/d/82/last-updated?orgId=1) dashboard - in case of "your" dashboard this (dashboard documentation):
<img width="890" alt="Zrzut ekranu 2024-05-24 o 10 42 47" src="https://github.com/cncf/gitdm/assets/2469783/3f850675-0f0d-4834-a6dc-183a2e295fdc">

So metric file name is [project_developer_stats](https://github.com/cncf/devstats/blob/master/metrics/shared/project_developer_stats.sql) and you are looking for quarterly time range (q) so you open [Last Updated](https://opentelemetry.devstats.cncf.io/d/82/last-updated?orgId=1) and look for `metric name`: `project_developer_stats q` which will tell you when it was last calculated...

Currently from materilized table:
```
opentelemetry=# select split_part(name, '$$$', 1) as contributor, split_part(name, '$$$', 2) as company, value as contributions from shdev where series like 'hdev_contributionsopentelemetrycommunityall%' and period = 'q' and name like 'ralf0131%' limit 5;
 contributor |    company    | contributions 
-------------+---------------+---------------
 ralf0131    | Alibaba Group |             6
(1 row)
```
<img width="2426" alt="Zrzut ekranu 2024-05-24 o 11 04 23" src="https://github.com/cncf/gitdm/assets/2469783/c6f3cc51-b6d7-4975-a989-e71e721ab26b">
<img width="2560" alt="Zrzut ekranu 2024-05-24 o 11 05 34" src="https://github.com/cncf/gitdm/assets/2469783/50f3773f-d793-4028-89e9-c5036a2263db">

**Comment by lukaszgryglicki** [comment]
Closing as all is working as expected.

**Comment by steverao** [comment]
>  please note that those dashboards are NOT realtime - 1st - affiliations are imported once / 4 weeks

I still have a problem about it. I created the [PR](https://github.com/cncf/gitdm/pull/338) to add affiliation information for my all colleagues in April 12th, but why aren't `ralf0131` and `wgy035` updated?

**Comment by lukaszgryglicki** [comment]
<img width="2353" alt="Zrzut ekranu 2024-05-24 o 12 10 08" src="https://github.com/cncf/gitdm/assets/2469783/dc94e590-2557-4f5a-914e-8ad2fc1af324">
<img width="2446" alt="Zrzut ekranu 2024-05-24 o 12 10 30" src="https://github.com/cncf/gitdm/assets/2469783/96547dce-1076-4083-a1ae-20d2b8688523">

**Comment by steverao** [comment]
My question is why they weren’t updated at first？Is the problem of data importing?

**Comment by lukaszgryglicki** [comment]
Affiliations are imported once / month, in case of opentelemetry this is:
```
root@devstats-node-2:~/go/src/github.com/cncf/devstats-k8s-lf/util# k get cj | grep affiliations-opentelemetry
devstats-affiliations-opentelemetry             0 11 6 * *                               False     0        162m            3y153d
```

Then the dashboards are updated depending on which time range is calculated, for example quarterly dashboards need to be updated once / 3 months.

I still don't get what is the problem here, I've also provided a link where you can check where given dashboard was last updated.

**Comment by steverao** [comment]
> I still don't get what is the problem here, I've also provided a link where you can check where given dashboard was last updated.

Thank you for your answer above, I learned a lot about the principle of dashboard running. My question is that I create a [PR](https://github.com/cncf/gitdm/pull/338/files) to maintain my all colleagues together. 

![image](https://github.com/cncf/gitdm/assets/25423978/a89bd5e1-69ed-40a4-b355-98cc40174a7a)

According to description you mentioned  below:
> affiliations are imported once / 4 weeks and dashboards are generated at given point in time and "saved" in precomputed tables so they are quickly displayed on the UI

I think their affiliation will be updated together. But some people once finish some contributions, they can see their affiliation in dashboard quickly, why some people like `ralf0131` can't? It's also the reason of dashboard updating? 
 
![image](https://github.com/cncf/gitdm/assets/25423978/8bbe24c7-da87-485d-8087-2ebb7574a037)
