### ISSUE TITLE
Country name not displayed on K8s devstats

### ISSUE THREAD

**Issue by dipesh-rawat** [cncf/gitdm#432]
I am unable to see "Country" name displayed in the k8s devstats for my username `dipesh-rawat`; it appears as blank. 

<img width="1255" alt="k8s-devstats" src="https://github.com/user-attachments/assets/54e26eb7-f225-4d43-8c2a-dcfcec72fa66">

Reference Link to verify the issue: [k8s.devstats.cncf.io (click here)](https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1&var-period_name=Last%206%20months&var-repogroups=SIG%20Docs&var-repos=All&var-companies=All&var-countries=All)

I would like to request adding country, “United Kingdom” to be visible for username `dipesh-rawat` on the k8s devstats dashboard.

**Comment by dipesh-rawat** [comment]
After some investigation, it seems that the [github_users.json](https://github.com/cncf/gitdm/blob/master/src/github_users.json)  data might be incorrect _(country_id)_ for my entry, which could potentially be causing this issue. 

@lukaszgryglicki could you please assist in resolving this? Your help would be greatly appreciated. Thank you!

**Comment by lukaszgryglicki** [comment]
I will update the JSON and next time affiliations are import it will be updated.

**Comment by lukaszgryglicki** [comment]
Hmmm - I see that your country ID is correct:
<img width="920" alt="Zrzut ekranu 2024-07-15 o 07 25 40" src="https://github.com/user-attachments/assets/b3505dc0-ee0e-42c2-94fa-5403b767fd75">

Also in the database:
```
gha=# select * from gha_actors where login = 'dipesh-rawat';
    id    |    login     |     name     | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
----------+--------------+--------------+------------+-----+----------+----+-----------+--------------+-----
 13051389 | dipesh-rawat | Dipesh Rawat | uk         |     |          |    |           |              |    
(1 row)
```

Maybe it was changed recently and dashboard was not regenerated yet, I'll refresh it manually to see if that helps...

**Comment by lukaszgryglicki** [comment]
I've regenerated the dashboard but still can't see your country, so this is something else, investigating, will LYK when I find something...

**Comment by lukaszgryglicki** [comment]
Right.... the country code should actually be `gb` not `uk` and this is the issue, regenerating again...

**Comment by lukaszgryglicki** [comment]
Fixed @dipesh-rawat - see [this](https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1&var-period_name=Last%206%20months&var-repogroups=SIG%20Docs&var-repos=All&var-companies=All&var-countries=United%20Kingdom).

**Comment by dipesh-rawat** [comment]
@lukaszgryglicki Thanks for the quick resolution! On the other activities dashboard ([k8s.devstats.cncf.io (click here)](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%206%20months&var-metric=contributions&var-repogroup_name=All&var-repo_name=&var-country_name=United%20Kingdom&var-companies=All)), my username isn't showing under the search results by country 'United Kingdom' yet, but I assume this will be fixed once the dashboard data is refreshed according to the regular schedule. Is that correct?

**Comment by lukaszgryglicki** [comment]
Yes, I've refreshed only that single dashboard.
