### ISSUE TITLE
I added my company information, but I don't seem to see any association between me and my company from this table.

### ISSUE THREAD

**Issue by luomengY** [cncf/gitdm#458]
I added my company information(https://github.com/cncf/gitdm/pull/455), but I don't seem to see any association between me and my company from this table(https://kubeedge.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1).
![image](https://github.com/user-attachments/assets/14895dc2-e3eb-41cb-b9f9-1776c89a20f7)

**Comment by lukaszgryglicki** [comment]
Affiliation data is refreshed once per 4 weeks, only one week passed or so - closing this, please reopen if not refreshed after 4 weeks.
