### ISSUE TITLE
Why is my name inside the lista?

### ISSUE THREAD

**Issue by jonas4040** [cncf/gitdm#60]
I really, really must know why, I dont remember to have contributted to this repo.

You have the obbligation to explain me this, please.

**Comment by jonas4040** [comment]
I beg your pardon, I installed cloud foundry this weak. But please answer me this question and I'll close pra delete this issue

**Comment by lukaszgryglicki** [comment]
Your name is there because you contributed to some project tracked here. I can remove it if you want this, just let me know and it will be removed and added to `forbiden list` so it won't apear there anymore.

**Comment by jonas4040** [comment]
> Your name is there because you contributed to some project tracked here. I can remove it if you want this, just let me know and it will be removed and added to `forbiden list` so it won't apear there anymore.

No, it's not necessary, thank you for your fast reply, probably I am going to delete this issue soon.
